// Code generated by "stringer -type=Product"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Tshirt-0]
	_ = x[Mug-1]
	_ = x[Hat-2]
	_ = x[Book-3]
	_ = x[Jar-4]
}

const _Product_name = "TshirtMugHatBookJar"

var _Product_index = [...]uint8{0, 6, 9, 12, 16, 19}

func (i Product) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Product_index)-1 {
		return "Product(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Product_name[_Product_index[idx]:_Product_index[idx+1]]
}
